<?php
session_start();
require_once 'config/db.php';
require_once 'fpdf186/fpdf.php';  // Adjust path if needed

if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit();
}

if (!isset($_GET['booking_id'])) {
    echo "Invalid access.";
    exit();
}

$booking_id = intval($_GET['booking_id']);
$user_id = $_SESSION['user_id'];

// Fetch booking details
$query = "SELECT b.*, m.title, m.poster_url FROM bookings b 
          JOIN movies m ON b.movie_id = m.id 
          WHERE b.id = ? AND b.user_id = ?";
$stmt = $conn->prepare($query);
$stmt->bind_param("ii", $booking_id, $user_id);
$stmt->execute();
$result = $stmt->get_result();
$booking = $result->fetch_assoc();

if (!$booking) {
    echo "❌ Booking not found.";
    exit();
}

// If verified and download request exists, generate PDF using FPDF
if (isset($_GET['download']) && $booking['status'] === 'verified') {
    class PDF extends FPDF {
        function Header() {
            $this->Image('assets/Yellow Brown Illustration Cinema Ticket.png', 10, 6, 30); // Cinema logo
            $this->SetFont('Arial', 'B', 20);
            $this->Cell(0, 10, 'Cinema Ticket', 0, 1, 'C');
            $this->Ln(5);
        }

        function Footer() {
            $this->SetY(-15);
            $this->SetFont('Arial', 'I', 8);
            $this->Cell(0, 10, 'Generated by Cinema Ticketing System', 0, 0, 'C');
        }

        function TicketRow($iconPath, $label, $value, $y) {
            $this->Image($iconPath, 15, $y, 7, 7); // Icon
            $this->SetXY(25, $y);
            $this->SetFont('Arial', 'B', 12);
            $this->Cell(35, 7, $label, 0, 0);
            $this->SetFont('Arial', '', 12);
            $this->Cell(0, 7, $value, 0, 1);
        }
    }

    $pdf = new PDF();
    $pdf->AddPage();
    $startY = 50;

    $pdf->TicketRow('assets/movie.png', 'Movie:', $booking['title'], $startY);
    $pdf->TicketRow('assets/calendar.png', 'Date:', $booking['screening_day'], $startY + 10);
    $pdf->TicketRow('assets/clock.png', 'Time:', $booking['screening_time'], $startY + 20);
    $pdf->TicketRow('assets/seat.png', 'Seats:', $booking['seats'], $startY + 30);
    $pdf->TicketRow('assets/price.png', 'Total Price:', $booking['total'].' PKR', $startY + 40);
    $pdf->TicketRow('assets/id.png', 'Booking ID:', $booking['id'], $startY + 50);
    $pdf->TicketRow('assets/verified.png', 'Status:', 'Verified', $startY + 60);

    // Optional QR Code Placeholder
    $pdf->SetXY(150, 100);
    $pdf->Rect(150, 100, 40, 40);
    $pdf->SetFont('Arial', 'I', 8);
    $pdf->SetXY(152, 120);
    $pdf->Cell(0, 5, 'Scan to verify', 0);

    $pdf->Output("D", "ticket_{$booking['id']}.pdf");
    exit();
}

?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Download Ticket</title>
  <style>
    body {
        font-family: Arial, sans-serif;
        text-align: center;
        margin-top: 80px;
    }
    .message {
        font-size: 24px;
        margin-bottom: 20px;
        color: #333;
    }
    .download-btn {
        display: inline-block;
        padding: 12px 24px;
        background-color: #28a745;
        color: white;
        text-decoration: none;
        border-radius: 6px;
        font-size: 18px;
    }
  </style>
</head>
<body>

<?php if ($booking['status'] === 'verified'): ?>
    <div class="message">🎉 Your booking has been verified!</div>
    <a href="download_ticket.php?booking_id=<?= $booking_id ?>&download=1" class="download-btn">Download Ticket</a>
<?php else: ?>
    <div class="message">⏳ Your booking is awaiting admin approval.</div>
<?php endif; ?>

</body>
</html>
